### ISSUE TITLE
Plugin code slug/prefix and CONSTANTS

### ISSUE THREAD

**Issue by Remzi1993** [Ramoonus/jquery-updater#119]
Ik stel voor om alle slugs gelijk te maken.

Ik had namelijk voor mijn eigen plugin dit gedaan:
Mijn plugin heette: **WP jQuery Updater**
Slug in code: **wpj_updater_plugin** (alle code begon met deze prefix)
CONSTANT slug: **WPJ_UPDATER_PLUGIN** (alle constants begonnen met deze prefix)

Ik stel het volgende voor:
De plugin heet: **jQuery Updater**
Slug in code: **jquery_updater_plugin** (prefix voor alle code)
CONSTANT slug: **JQUERY_UPDATER_PLUGIN** (prefix voor alle constants)

Dit om verwarring te voorkomen, want ju_plugin of j_updater_plugin is onduidelijk of staat niet.
Ik kon dit niet doen, anders werd het te lang, maar jij wel.

Zou je ook de GitHub repository naam in kleine letters willen wijzigen? Dit is voor mij wat makkelijker te werken. Ik moet nu steeds de hoofdletters voor het clonen in kleine letters veranderen. Dit maakt het ook voor anderen die mogelijk in de toekomst willen meehelpen makkelijker om het gelijk te clonen in een WordPress local setup.

**Comment by Ramoonus** [comment]
plugin renamed to jquery-updater

**Comment by Remzi1993** [comment]
Thanks! En wat vind je van de rest?
