### ISSUE TITLE
jQuery 3.4.1

### ISSUE THREAD

**Issue by nicwise** [Ramoonus/jquery-updater#121]
Hi

Any plans to integrate 3.4.1? I'm happy to do a PR for it.

Thanks

**Comment by nicwise** [comment]
and here's a PR

https://github.com/Ramoonus/jquery-updater/pull/122

**Comment by Ramoonus** [comment]
the plugin on Subversion and wordpress.org is up to date
git is lacking behind

**Comment by nicwise** [comment]
Thanks. We use composer, so git is the main source, I think.
