### ISSUE TITLE
wp_register_script() instead of wp_enqueue_script()?

### ISSUE THREAD

**Issue by puggan** [Ramoonus/jquery-updater#123]
the use of wp_enqueue_script() forces jQuery to be loaded on pages where it's not needed,
replacing them with wp_register_script() should make it only load the right jQuery, if jQuery is dependent by any other script.

Wanted to do PR insted, but the master branch is out of date...

**Comment by puggan** [comment]
We are currenlty using this patch:
[register_instead_of_enqueue.patch.txt](https://github.com/Ramoonus/jquery-updater/files/3814099/register_instead_of_enqueue.patch.txt)

**Comment by Ramoonus** [comment]
will do it on SVN while I update the readme

**Comment by lydenyardley** [comment]
Any update on this issue? I'm trying to stop the plugin loading jQuery on most pages of my website, which I usually use AssetCleanup for... but it doesn't even see your plugin's jQuery script!?

**Comment by Ramoonus** [comment]
https://wordpress.org/plugins/wp-asset-clean-up/
it should see my plugin

**Comment by Ramoonus** [comment]
3.4.1.3 is commited right now

**Comment by lydenyardley** [comment]
@Ramoonus That's the right 'Asset Cleanup' that you've linked, but I can confirm, it doesn't see your script (on my site at least).

What's new in 3.4.1.3?

**Comment by Ramoonus** [comment]
i`ve changed enqueue to register as in the past

**Comment by lydenyardley** [comment]
Hey @Ramoonus when is this getting released? I thought it was being pushed to the updates last week?

**Comment by Ramoonus** [comment]
i haven`t done an update last week!?
