### ISSUE TITLE
composer install errors, Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by lkrubner** [Ramoonus/jQuery-Updater#91]
Is anyone else having trouble installing this via Composer? 

      composer update
      Loading composer repositories with package information
      Updating dependencies (including require-dev)                                                         
      Your requirements could not be resolved to an installable set of packages.
      
        Problem 1
          - The requested package ramoonus/jquery-updater could not be found in any version, there may be a typo in the package name.
      
      Potential causes:
       - A typo in the package name
       - The package is not available in a stable-enough version according to your minimum-stability setting
      
Some of what I am seeing:

http://krubner.com/composer-jquery_update_1.png

http://krubner.com/composer-jquery_update_2.png

http://krubner.com/composer-jquery_update_3.png

In our project composer.json I don't see anything that would conflict with this plugin: 

    "minimum-stability": "dev",

We have WordPress 4.4.1 installed. 

      {
        "url": "git@github.com:Ramoonus/jQuery-Updater.git",
        "type": "vcs"
      },

Elsewhere: 

      "guzzlehttp/guzzle": "~5.0",
      "facebook/php-sdk-v4" : "4.0.*",
      "Ramoonus/jQuery-Updater" : "3.*"  

Why wouldn't this work?

**Comment by Ramoonus** [comment]
I haven`t tested it yet 
but it looks like ìt doesn`t work because no versions have been tagged on GH

**Comment by lkrubner** [comment]
Even this doesn't work:


  "Ramoonus/jQuery-Updater" : "*"

**Comment by lkrubner** [comment]
How is this normally installed?

**Comment by Ramoonus** [comment]
the stable is at https://wordpress.org/plugins/jquery-updater/

**Comment by lkrubner** [comment]
At my company we have plugins in .gitignore, so simply downloading and installing the plugin won't actually do anything for me, as I won't be able to get that into git. But I can edit the composer.json file, so I was hoping to take that method to install the plugin. You seem to have a valid composer.json file for your project, so I'm confused why there is any error.

**Comment by lkrubner** [comment]
Ah, I see. The other repos (which work with Composer) have a "dist" in their composer.json. Perhaps that is what you are missing. I see this as an example that is working for us: 

      {
        "name": "openroadmedia/openroad-optimizely-plugin",
        "type": "wordpress-plugin",
        "version": "master",
        "dist": {
          "url": "git@github.com:openroadmedia/openroad-optimizely-plugin.git",
          "type": "git"
        }
      }

**Comment by Ramoonus** [comment]
won`t fix for now
